version: '3'

services:
  app:
    image: alan/cursosp
    ports:
      - 3000:3000
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: alan-cursos
    ports:
      - 27017:27017
